### ISSUE TITLE
Custom social navigation layer for ROS2 don't work

### ISSUE THREAD

**Issue by NamTruongTran0** [dharanish-nh/customcostmap#1]
Hey :),

first i would like to thank you for your contributions. Your postings have accelerated my project. 

i curently trying to implement the social navigation layer for ROS2 foxy:
https://github.com/robotics-upo/nav2_social_costmap_plugin

I cloned the social navigation layer and the people_msg repository in my workspace. Colcon build showing no errors. After that i change my params.yaml file.  Unfortunately the social_layer not showing up?
Can you help me out?

https://www.youtube.com/watch?v=QfGq5oc1GSk

Thank you so much.

**Comment by dharanish-nh** [comment]
/Hello Namo,

There is minor difference in costmap plugin between humble and foxy with regard to syntax in code. For example "node" in foxy becomes "auto node" pointer. 

Yes I published people message separately with gazebo actor model position. By doing so the plugin worked. But the robot was not moving. 
Whenever I turned of the planner the robot started to move.

Turning on social layer in global planner or local planner will make the respective planner not to work.

One of the reason for this can be high computation  by the plugin code.and is not allowing robot to move around.

I also tried to simplify it so that the layer gets activated whenever the human model is within 6m still . I got the same result. I am kind of stuck here and left it at this point. 

I would be happy to help you out but I am not sure where exactly is the problem.

I hope my comment will help you.

**Comment by dharanish-nh** [comment]
If you have any ideas @Namo98 . Will be helpful to solve it

**Comment by Namo98** [comment]
Thank you so much for your fast reply. 
I using pedsim to simulate the agents (maybe this will work instead of your gazebo actor model).

Is the `/pedsim_simulator/simulated_agents` topic data important to publish to the /people topic:
https://streamable.com/xrmxqx

Or is the `/pedsim_visualizer/tracked_persons` topic data important to publish to the /people topic?:
https://streamable.com/kxi96k

So I have to subscribe to the `/pedsim_simulator/simulated_agents` topic **or** `/pedsim_visualizer/tracked_persons` and then publish the data to the /people topic right? So the social navigation layer can subscribe to the /people topic get the data of the agents to create a layer around the agents?

I think i just have to publish on the /people topic then the layer will work.
Can you show me how you publish to /people topic?:


Maybe we can discuss this on discord?

**Comment by dharanish-nh** [comment]
Check the message type of both the topics and match it with people message type.

Yes that's right. I wrote a simple code to subscribe to position data of  gazebo actor models through gazebo model states topic. Then use that data to publish people message. That should work.

**Comment by NamTruongTran** [comment]
Can you provide me the code?

This would help me a lot :)
